USERS = [
    {
        "name": "Vitor Ferreira",
        "dob": "1998-05-25",
        "email": "vitorferreira@outlook.com",
        "password_hash": "hashed_password_1",
        "vat_number": "123567987",
        "address_1": "Rua das Flores, 123",
        "address_2": "Rua das Acacias, 876",
        "role": "user",

    },
    {
        "name": "Ana Souza",
        "dob": "1998-09-23",
        "email": "ana.souza@gmail.com",
        "password_hash": "hashed_password_2",
        "vat_number": "987654321",
        "address_1": "Avenida Central, 456",
        "address_2": "Rua das Estrelas, 78",
        "role": "user",
    },
    {
        "name": "Joao Santana",
        "dob": "1967-02-21",
        "email": "joaosantana@gmail.com",
        "password_hash": "hashed_password_3",
        "vat_number": "9076548756",
        "address_1": "Travessa Cariri, 2384",
        "address_2": "Rua do Carmo, 900",
        "role": "user",
    },
    {
        "name": "Joab Queiroz",
        "dob": "1968-09-01",
        "email": "joab.queiroz@outlook.com",
        "password_hash": "hashed_password_4",
        "vat_number": "987644321",
        "address_1": "Rua da Cerca, 7",
        "address_2": "Avenida Vasco da Gama, 124",
        "role": "user",
    },
    {
        "name": "Sergio Morais",
        "dob": "1989-09-24",
        "email": "serginho@gmail.com",
        "password_hash": "hashed_password_5",
        "vat_number": "987644321",
        "address_1": "Rua da Loja, 89",
        "address_2": "Avenida Vasco Coutinho, 678",
        "role": "user",
    },
    {
        "name": "Fernando Paiva",
        "dob": "1991-09-17",
        "email": "fernando.paiva@outlook.com",
        "password_hash": "hashed_password_6",
        "vat_number": "654654654",
        "address_1": "Avenida Obral, 1267",
        "address_2": "Avenida Sobralense, 1",
        "role": "user",
    },
    {
        "name": "Neymar da Silva",
        "dob": "1990-09-17",
        "email": "neymarjunior@outlook.com",
        "password_hash": "hashed_password_7",
        "vat_number": "123456990",
        "address_1": "Rua Fernando Namora, 23",
        "address_2": "Rua Porto, 6",
        "role": "user",
    },
    {
        "name": "Robinho Lopes",
        "dob": "1986-02-16",
        "email": "robinhojr@gmail.com",
        "password_hash": "hashed_password_8",
        "vat_number": "123456787",
        "address_1": "Rua Fernando Brasil, 65",
        "address_2": "Rua Lisboa, 9",
        "role": "user",
    },
    {
        "name": "Rita Castro",
        "dob": "1960-09-17",
        "email": "ritabreu@outlook.com",
        "password_hash": "hashed_password_9",
        "vat_number": "803456987",
        "address_1": "Rua Nova, 623",
        "address_2": "Rua Braga, 98",
        "role": "user",
    },
    {
        "name": "Edna Sousa",
        "dob": "1999-04-17",
        "email": "ednasousa@hotmail.com",
        "password_hash": "hashed_password_10",
        "vat_number": "888456987",
        "address_1": "Rua Fernando Sousa, 283",
        "address_2": "Avenida Rio de Janeiro, 66",
        "role": "user",
    },
    {
        "name": "Natanael Bruno",
        "dob": "1990-09-17",
        "email": "natanbruno@outlook.com",
        "password_hash": "hashed_password_11",
        "vat_number": "773456998",
        "address_1": "Rua Luis Namora, 293",
        "address_2": "Rua Luis Gomes, 6",
        "role": "user",
    },
    {
        "name": "Maria Cleide",
        "dob": "1940-09-17",
        "email": "cleideestevao@hotmail.com",
        "password_hash": "hashed_password_12",
        "vat_number": "128956987",
        "address_1": "Rua Cariri, 2384",
        "address_2": "BR 222 Km 06, 890",
        "role": "user",
    },
    {
        "name": "Helder Lopes",
        "dob": "1987-09-23",
        "email": "helderlopes@gmail.com",
        "password_hash": "hashed_password_13",
        "vat_number": "111456987",
        "address_1": "Rua Luis Junior, 2323",
        "address_2": "Rua Amaral Sousa, 6",
        "role": "user",
    },
    {
        "name": "Cayke Levi",
        "dob": "1981-09-03",
        "email": "caykelevi@hotmail.com",
        "password_hash": "hashed_password_14",
        "vat_number": "111123987",
        "address_1": "Rua Moraes, 1256",
        "address_2": "Rua Sao Luiz Moraes, 56",
        "role": "user",
    },
    {
        "name": "Carla Mikaele",
        "dob": "1997-09-21",
        "email": "carlafrota@gmail.com",
        "password_hash": "hashed_password_15",
        "vat_number": "786456987",
        "address_1": "Rua Gadelha, 67",
        "address_2": "Rua Luiz Junior, 6",
        "role": "user",
    },
    {
        "name": "Carlos Lopes",
        "dob": "1977-09-09",
        "email": "carloslopes@hotmail.com",
        "password_hash": "hashed_password_16",
        "vat_number": "901456987",
        "address_1": "Rua Sobral, 2323",
        "address_2": "Rua Para, 600",
        "role": "admin",
    },
    {
        "name": "Ana Thais",
        "dob": "1979-01-29",
        "email": "anathais@outlook.com",
        "password_hash": "hashed_password_17",
        "vat_number": "901456089",
        "address_1": "Rua Napoleao Bonaparte, 323",
        "address_2": "Praceta Liz Gomes, 800",
        "role": "admin",
    },
    {
        "name": "Elieser Santos",
        "dob": "1999-02-09",
        "email": "kalebe@gmail.com",
        "password_hash": "1234",
        "vat_number": "901456089",
        "address_1": "Rua Napoleao Bonaparte, 323",
        "address_2": "Praceta Liz Gomes, 800",
        "role": "admin",
    },
]

WINES = [
    {
        "brand": "Rosa Negra",
        "name": "Tinto",
        "price": "29.99",
        "type": "Mesa",
        "alcohol": "12.5%",
        "year": "2024",
        "region": "Alentejo",
        "description": "Um vinho simples e versátil, com notas de frutas vermelhas maduras e um toque suave de especiarias. ",
    },
    {
        "brand": "Rosa Negra",
        "name": "Branco",
        "price": "29.99",
        "type": "Mesa",
        "alcohol": "12.5%",
        "year": "2025",
        "region": "Alentejo",
        "description": "Um vinho branco fresco e vibrante, com aromas de limão, maçã verde e notas minerais características da casta Arinto. ",
    },
    {
        "brand": "Rosa Negra",
        "name": "Tinto",
        "price": "49.99",
        "type": "Reserva",
        "alcohol": "14%",
        "year": "2025",
        "region": "Alentejo",
        "description": "Um tinto encorpado e elegante, com aromas de frutas negras maduras, notas de especiarias e um toque de carvalho. ",
    },
    {
        "brand": "Rosa Negra",
        "name": "Branco Frizante",
        "price": "89.99",
        "type": "Exotico",
        "alcohol": "10.5%",
        "year": "2024",
        "region": "Alentejo",
        "description": "Um vinho leve e aromático, com notas tropicais de maracujá e abacaxi, além de um toque cítrico refrescante.",
    },
    {
        "brand": "Rosa Negra",
        "name": "Rose",
        "price": "69.99",
        "type": "Exotico",
        "alcohol": "11.5%",
        "year": "2024",
        "region": "Alentejo",
        "description": "Um rosé vibrante e delicado, com aromas de frutos vermelhos frescos, como morango e framboesa e um toque floral.  ",
    },
    {
        "brand": "Rosa Negra",
        "name": "Verde",
        "price": "79.99",
        "type": "Exotico",
        "alcohol": "11.5%",
        "year": "2024",
        "region": "Alentejo",
        "description": "Um vinho jovem e fresco, com notas cítricas de limão e toranja, complementadas por nuances tropicais de manga e melão.",
    },
    {
        "brand": "Rosa Negra",
        "name": "Tinto",
        "price": "115.99",
        "type": "Signature",
        "alcohol": "14.5%",
        "year": "2025",
        "region": "Alentejo",
        "description": "Um tinto sofisticado e intenso, com aromas de amora, cassis e notas de especiarias, como pimenta preta e cravo. ",
    },
    {
        "brand": "Rosa Negra",
        "name": "Branco",
        "price": "115.99",
        "type": "Signature",
        "alcohol": "13%",
        "year": "2025",
        "region": "Alentejo",
        "description": "Um branco elegante e complexo, com aromas de pêra, maçã verde e notas sutis de baunilha e flores brancas. ",
    },
]

STOCK = [

    {
        "fk_wine": 1,
        "movement": "purchase",
        "quantity": 50,
        "fk_user": 2,
        "reason": "Reabastecimento inicial",
    },
    {
        "fk_wine": 2,
        "movement": "sale",
        "quantity": -5,
        "fk_user": 3,
        "reason": "Venda online",
    },
    {
        "fk_wine": 3,
        "movement": "adjustment",
        "quantity": -2,
        "fk_user": 4,
        "reason": "Quebra de garrafa",
    },
    {
        "fk_wine": 4,
        "movement": "purchase",
        "quantity": 100,
        "fk_user": 5,
        "reason": "Reestoque automático",
    },
    {
        "fk_wine": 5,
        "movement": "sale",
        "quantity": -20,
        "fk_user": 6,
        "reason": "Venda em loja física",
    },
    {
        "fk_wine": 6,
        "movement": "adjustment",
        "quantity": 5,
        "fk_user": None,
        "reason": "Correção de inventário",
    },
    {
        "fk_wine": 7,
        "movement": "purchase",
        "quantity": 30,
        "fk_user": 7,
        "reason": "Reabastecimento inicial",
    },
    {
        "fk_wine": 8,
        "movement": "sale",
        "quantity": -3,
        "fk_user": 8,
        "reason": "Venda online",
    },
    {
        "fk_wine": 1,
        "movement": "sale",
        "quantity": -10,
        "fk_user": 9,
        "reason": "Venda online",
    },
    {"fk_wine": 2,
     "movement": "adjustment",
     "quantity": 7,
     "fk_user": 10,
     "reason": "Ajuste manual",
     },
    {
        "fk_wine": 3,
        "movement": "purchase",
        "quantity": 40,
        "fk_user": 11,
        "reason": "Reestoque automático",
    },
    {
        "fk_wine": 4,
        "movement": "sale",
        "quantity": -15,
        "fk_user": 12,
        "reason": "Venda para evento",
    },
    {
        "fk_wine": 5,
        "movement": "purchase",
        "quantity": 25,
        "fk_user": 13,
        "reason": "Reabastecimento",
    },
    {
        "fk_wine": 6,
        "movement": "adjustment",
        "quantity": -1,
        "fk_user": None,
        "reason": "Descarte por validade",
    },
    {
        "fk_wine": 7,
        "movement": "sale",
        "quantity": -8,
        "fk_user": 14,
        "reason": "Venda online",
    },
    {
        "fk_wine": 8,
        "movement": "purchase",
        "quantity": 60,
        "fk_user": 15,
        "reason": "Reabastecimento inicial",
    },
    {
        "fk_wine": 1,
        "movement": "adjustment",
        "quantity": 10,
        "fk_user": 16,
        "reason": "Contagem cíclica",
    },
    {
        "fk_wine": 2,
        "movement": "sale",
        "quantity": -12,
        "fk_user": 17,
        "reason": "Venda corporativa",
    },
    {
        "fk_wine": 3,
        "movement": "purchase",
        "quantity": 45,
        "fk_user": 18,
        "reason": "Promoção de fornecedor",
    },
    {
        "fk_wine": 4,
        "movement": "adjustment",
        "quantity": 3,
        "fk_user": None,
        "reason": "Correção por entrada duplicada",
    },
    {
        "fk_wine": 5,
        "movement": "sale",
        "quantity": -18,
        "fk_user": 1,
        "reason": "Venda direta",
    },
    {
        "fk_wine": 6,
        "movement": "purchase",
        "quantity": 20,
        "fk_user": 2,
        "reason": "Reabastecimento semanal",
    },
    {
        "fk_wine": 7,
        "movement": "sale",
        "quantity": -10,
        "fk_user": 3,
        "reason": "Venda online",
    },
    {
        "fk_wine": 8,
        "movement": "adjustment",
        "quantity": 2,
        "fk_user": 4,
        "reason": "Ajuste manual",
    },
]

PURCHASES = [
    {
        "fk_user": 2,
        "total_value": 199.95,
    },
    {
        "fk_user": 3,
        "total_value": 49.99,
    },
    {
        "fk_user": 4,
        "total_value": 89.97,
    },
    {
        "fk_user": 5,
        "total_value": 179.95,
    },
    {
        "fk_user": 6,
        "total_value": 39.99,
    },
    {
        "fk_user": 7,
        "total_value": 349.93,
    },
    {
        "fk_user": 8,
        "total_value": 139.96,
    },
    {
        "fk_user": 9,
        "total_value": 29.99,
    },
    {
        "fk_user": 10,
        "total_value": 79.98,
    },
    {
        "fk_user": 11,
        "total_value": 399.90,
    },
    {
        "fk_user": 12,
        "total_value": 99.99,
    },
    {
        "fk_user": 13,
        "total_value": 259.96,
    },
    {
        "fk_user": 14,
        "total_value": 159.95,
    },
    {
        "fk_user": 15,
        "total_value": 349.92,
    },
    {
        "fk_user": 16,
        "total_value": 189.95,
    },
    {
        "fk_user": 17,
        "total_value": 59.99,
    },
    {
        "fk_user": 18,
        "total_value": 499.90,
    },
    {
        "fk_user": 1,
        "total_value": 79.99,
    },
]

PURCHASE_ITEMS = [

    {
        "fk_purchase": 1,
        "fk_wine": 1,
        "quantity": 2,
    },
    {
        "fk_purchase": 1,
        "fk_wine": 3,
        "quantity": 3,
    },
    {
        "fk_purchase": 2,
        "fk_wine": 2,
        "quantity": 1,
    },
    {
        "fk_purchase": 3,
        "fk_wine": 4,
        "quantity": 5,
    },
    {
        "fk_purchase": 4,
        "fk_wine": 5,
        "quantity": 4,
    },
    {
        "fk_purchase": 5,
        "fk_wine": 6,
        "quantity": 1,
    },
    {
        "fk_purchase": 6,
        "fk_wine": 7,
        "quantity": 7,
    },
    {
        "fk_purchase": 7,
        "fk_wine": 8,
        "quantity": 3,
    },
    {
        "fk_purchase": 8,
        "fk_wine": 1,
        "quantity": 1,
    },
    {
        "fk_purchase": 9,
        "fk_wine": 2,
        "quantity": 2,
    },
    {
        "fk_purchase": 10,
        "fk_wine": 3,
        "quantity": 10,
    },
    {
        "fk_purchase": 11,
        "fk_wine": 4,
        "quantity": 2,
    },
    {
        "fk_purchase": 12,
        "fk_wine": 5,
        "quantity": 6,
    },
    {
        "fk_purchase": 13,
        "fk_wine": 6,
        "quantity": 3,
    },
    {
        "fk_purchase": 14,
        "fk_wine": 7,
        "quantity": 5,
    },
    {
        "fk_purchase": 15,
        "fk_wine": 8,
        "quantity": 4,
    },
    {
        "fk_purchase": 16,
        "fk_wine": 1,
        "quantity": 3,
    },
    {
        "fk_purchase": 17,
        "fk_wine": 2,
        "quantity": 1,
    },
    {
        "fk_purchase": 18,
        "fk_wine": 3,
        "quantity": 12,
    },
]
